FROM alpine:3.20 as build

RUN apk add go
WORKDIR /src
COPY . /src
RUN go build -o eburyweb tour/api/web/main.go

FROM alpine:3.20
COPY --from=build /src/eburyweb /
COPY data/input-routes.csv /
ENTRYPOINT /eburyweb input-routes.csv